---
- name: ping server
  ping:

- name: install gnupg, apt-transport-https
  apt:
    name:
      - apt-transport-https
      - gnupg
    state: present

- name: Get filebeat 7.17.14
  ansible.builtin.get_url:
    url: https://mirror.yandex.ru/mirrors/elastic/7/pool/main/f/filebeat/filebeat-7.17.14-amd64.deb
    dest: /home/gabber/

- name: Install filebeat
  apt:
    deb: /home/gabber/filebeat-7.17.14-amd64.deb 

- name: Copy config file for filebeat
  copy:
    src: /home/gabber/sys-diplom/ansible/roles/filebeat/files/filebeat.yml
    dest: /etc/filebeat
 
- name: nginx restart
  service:    
    name: nginx
    state: restarted   


- name: enable and restart filebeat
  ansible.builtin.systemd:
    name: filebeat
    enabled: true
    masked: no
    state: restarted


